### ISSUE TITLE
SBT is no longer available on ubuntu-latest image.

### ISSUE THREAD

**Issue by sageserpent-open** [guardian/gha-scala-library-release-workflow#50]
This is an FYI about the upgrade: https://github.com/actions/runner-images/issues/10636.

I've run into this in the CI build for Kinetic Merge (https://github.com/sageserpent-open/kineticMerge) and Americium (https://github.com/sageserpent-open/americium) - the latter uses *this project's* actions to publish releases.

It seems SBT has been dropped from Ubuntu-24.04; fortunately folks have kindly provided a new action to setup SBT in a workflow: (https://github.com/sbt/setup-sbt).

I've added the following stanza to the CI builds for Kinetic Merge and Americium:

```yaml
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      # New stanza....
      - uses: sbt/setup-sbt@v1
```

That sorts them both out nicely.

I can have a go at this myself when the next Americium release is due by forking this repository and playing around with pushing trial commits to GitHub, but it may be a lot quicker for the maintainers to do. Let me know if you're happy with amateur help. 😄
